### ISSUE TITLE
Delete chat

### ISSUE THREAD

**Issue by minzdrav** [kartikm7/llocal#5]
Hi @kartikm7 
It would be nice to have a small button in the chats list to remove the chat. 
![image](https://github.com/kartikm7/llocal/assets/1764392/575f2d18-322a-4af1-a302-bc89d21dcc64)

**Comment by kartikm7** [comment]
Hey @minzdrav ! Will add this in for the upcoming version as well. Planning to implement, PDF upload for this next release. But will add the chat delete feature as well. Thank you for the suggestion!

**Comment by kartikm7** [comment]
Hello @minzdrav ! I have worked on the deletion of chat [in this commit](https://github.com/kartikm7/llocal/commit/eeea62cf0265e6cfe9e5162edb2240af6d462ccf) , I'll close this issue as soon as the new beta version drops. If you want to try it out before that, you can run the build yourself (Doesn't take too long, just a few minutes) following the build scripts specified in the [readme](https://github.com/kartikm7/llocal) . Thank you for the suggestion!

**Comment by minzdrav** [comment]
Hi @kartikm7 
Yep, it's perfect! Thank you!

**Comment by kartikm7** [comment]
Hi @minzdrav ! Closing this issue, the new build is here with the delete chat feature. Thanks for the suggestion!
